### ISSUE TITLE
systemd fails to add dependency to the generated mount file: fsck invalid argument

### ISSUE THREAD

**Issue by nrvnrvn** [coreos/butane#136]
When configuring storage with the `with_mount_unit` option systemd complains about the fsck dependency.
Excerpt from the `.fcc` file:
```yaml
---
variant: fcos
version: 1.1.0

storage:
  disks:
    - device: /dev/vdb
  filesystems:
    - path: /var/srv
      device: /dev/vdb
      format: ext4
      label: var-srv
      with_mount_unit: true
```

Generated `.mount` file:
```
# /etc/systemd/system/var-srv.mount
# Generated by FCCT
[Unit]
Before=local-fs.target
Requires=systemd-fsck@/dev/vdb
After=systemd-fsck@/dev/vdb

[Mount]
Where=/var/srv
What=/dev/vdb
Type=ext4

[Install]
RequiredBy=local-fs.target
```

System logs:
```
Oct 06 08:25:09 lol-hostname systemd[1]: /etc/systemd/system/var-srv.mount:4: Failed to add dependency on systemd-fsck@/dev/vdb, ignoring: Invalid argument
Oct 06 08:25:09 lol-hostname systemd[1]: /etc/systemd/system/var-srv.mount:5: Failed to add dependency on systemd-fsck@/dev/vdb, ignoring: Invalid argument
```

```
$ rpm-ostree status
State: idle
Deployments:
● ostree://fedora:fedora/x86_64/coreos/stable
                   Version: 32.20200907.3.0 (2020-09-23T08:16:31Z)
                    Commit: b53de8b03134c5e6b683b5ea471888e9e1b193781794f01b9ed5865b57f35d57
              GPGSignature: Valid signature by 97A1AE57C3A2372CCA3A4ABA6C13026D12C944D0
```
