### ISSUE TITLE
Add local file embedding for SSH keys, systemd units and dropins

### ISSUE THREAD

**Issue by travier** [coreos/butane#179]
With https://github.com/coreos/fcct/pull/99, we can use the following FCC to embed files from a directory in a config:
```
storage:
  files:
    contents:
      local: foo.conf
```

I would like to use a similar mechanism to embed:
  * SSH Keys
  * systemd units
  * systemd dropins
