### ISSUE TITLE
Improve rendering of nesting levels in spec docs

### ISSUE THREAD

**Issue by bgilbert** [coreos/butane#183]
The config spec docs (for both Ignition and FCCT) have several levels of nested bullets, which are difficult to visually distinguish when reading the docs.  See if we can tweak the CSS on the docs sites to make the levels more distinctive.

**Comment by Okeanos** [comment]
Sooooo … I had a possible idea about how to approach that and whipped up a technical solution towards the whole "how to target the spec pages" when rending Markdown via GH Pages using just-the-docs without messing too much with [customization options](https://just-the-docs.github.io/just-the-docs/docs/customization/) (that all have to be maintained and make it difficult to keep the theme up to date).

Instead of having:

![Screenshot 2023-03-31 at 00 51 04](https://user-images.githubusercontent.com/887496/228982356-95c14b1c-7837-475d-9d5d-7068417acfc4.png)

I think something like the following _may_ improve the reading experience without you/us having to mess with the existing spec files:

![Screenshot 2023-03-31 at 00 50 36](https://user-images.githubusercontent.com/887496/228982455-ec43fbe8-b940-4a9b-b8d6-3cf43508e49d.png)


I admit that [the solution](https://github.com/Okeanos/butane/blob/spec-rendering-183/docs/_sass/custom/custom.scss) is somewhat … esoteric:

```scss
/*
 because we don't have a particular class at hand (or a unique id) to select the specification lists we do some
 CSS voodoo with selector syntax (https://www.w3.org/TR/selectors-3/#selectors) instead to target them based on context
 clues:
 select unordered lists that are preceded by an h1 element whose id attribute contains the substring "-specification-"
 */
h1[id*="-specification-"] ~ ul {
  ul {
    border-left: 1px solid $grey-lt-300;
  }

  li::before {
    content: unset;
    margin-left: unset;
    position: unset;
  }
}
```

I'm open to suggestions to make it prettier or attempt to solve it differently. However, from a glance at the docs of [just-the-docs](https://just-the-docs.github.io/just-the-docs/docs/customization/) and [Jekyll](https://jekyllrb.com/docs/front-matter/) there doesn't appear to be an easy/simple way to simply inject a standard CSS-class into particular pages.

if you want to see it live go to http://okeanos.github.io/butane/ (I suggest using a private Browser window to circumvent caching issues with the stylesheet).
