### ISSUE TITLE
Warn if partition number 0 specified with label from default OS image

### ISSUE THREAD

**Issue by bgilbert** [coreos/butane#243]
If the user specifies this:

```yaml
storage:
  disks:
    - device: /dev/sda
      partitions:
        - number: 0
          label: root
          size_mib: 12000
          resize: true
```

they probably meant `number: 4`.  The above will create an additional partition labeled `root`, rather than resizing the existing one.  See https://github.com/coreos/ignition/issues/1219 for details.

Add FCOS validation to check for default partlabels (`root`, `boot`, `EFI-SYSTEM`, `BIOS-BOOT`, etc.) and warn if the partition number is 0.  This is a reasonable warning even if we're not partitioning the boot disk, since udev can only create one partition symlink per partlabel for the whole system, and the user can easily choose another label.
