### ISSUE TITLE
Docs errors on ignition.proxy 

### ISSUE THREAD

**Issue by nsmith5** [coreos/butane#272]
The specification docs state that proxy configuration for ignition should be like

```yaml
ignition:
  proxy:
    # Note camel case
    httpProxy: string
    httpsProxy: string
    noProxy:
    - string
```

That is, it states camel case should be used. According to https://github.com/coreos/butane/blob/main/base/v0_4/schema.go#L188-L190, this should be snake case like

```yaml
ignition:
  proxy:
    # Note camel case
    http_proxy: string
    https_proxy: string
    no_proxy:
    - string
```
