### ISSUE TITLE
Validate merged/replaced Ignition configs if they're local/inline

### ISSUE THREAD

**Issue by bgilbert** [coreos/butane#275]
When merging/replacing a `local` or `inline` config, we already have the config contents, so we should run it through Ignition config validation to catch problems early.  (For example, the user may have provided a Butane config by mistake.)

**Comment by bfallik** [comment]
FWIW I believe I hit this exact problem recently with a snippet like:
```
variant: fcos
version: 1.4.0
ignition:
  config:
    merge:
    - local: fcos/nano.bu
      ...
```
I found an example elsewhere online that made me realize merged configs are meant to contain ignition and not butane.

It would be very helpful if [examples.md](https://github.com/coreos/butane/blob/main/docs/examples.md) illustrated this merge+local scenario.
