### ISSUE TITLE
compression: null is not working. 

### ISSUE THREAD

**Issue by grzebia** [coreos/butane#328]
Hi, 
recently I was trying to use "compression: null" in yaml file to turn off compression of some templated files. 
No matter how I tried part of user_data.json that shouldn't be compressed with gizp, are always gzipped. 

Input and output files in attachment. 

For example (it is taken from attachment):

```
   - path: /root/configure-agent-env.sh
      # 448 (decimal) == 700 (octal)
      mode: 448
      user:
        name: root
      group:
        name: root
      contents:
        compression: null
        inline: |
          #!/bin/bash

          set -x
          set -e
          set +u
```

is converted to:

```
        "path": "/root/configure-agent-env.sh",
        "user": {
          "name": "root"
        },
        "contents": {
          "compression": "gzip",
          "source": "data:;base64,H4sIAAAAAAAC/5RUbYsbtxN/r08xf/sPB2135bSFQJschLZHQsvdEafQUtJF1o69wrsaVTO6u23pdy+S7dhnO1zySrvz8HvQzO70f3rhvF4Y7pRiFKgeNgeW48ukVPLievgDqiVoFKvD2mlrKomJRTOlaFEbbzuKrCmgZzF2XVlTBxzgvWpJAQCg7Qgm98aJ8ytYUvx8sEkB4h4xwDesWvKolE4ci4UUWiNY7cDUsG7dlmSdFhg9CrJWNuyJpWdtMQpnCYvk2x5rG+Wk6VFWqdfv3t02t29vfvv95aRp9m9NMym5+ePkfJ+9vtmnds85rtwyX7CHyf//2eP9O4H334N06Dc3+BAoCuzzB/faiYQmRHoYXx4hXF5u7KC/c5H8gF7U0p0wzp+inJ/l5Eek889h3fk/T7nLHvB5+kB20Psxpin8ENEIgoE1jsG4WJZOOoQOjVSWvBjnMVZmhV5ASE3BWIvMpchTi0B3GIG5q+GNgGNIjMvUgxBQwGgE1RSch45YYKDkBbwZkIOxCMa3YELoR7Dkl26VohFHvlau3e5mFUBzvNODWfk06Jq5U7YbqIXZ89nsNDcVSrY7ievspykumshGMXfVGscVeqj+gkogsoHqGi4uyicsQzjuGO7OhZ8kOt9Wh7R4qjXX7Kx+e8bqMdOnlxbkKbxq2zLFkBa9s3lgZfB5TiZJR9H9jW2zxpFh6XqsDyYSieR0FgdRI58iAi4PmvQR6VZhT9b0WZMQrD3dN1kg7wbI1nh49vXzelbP6mcZ75g19/ht0zTv6XbVdrtWvH2V0RcIHNC6pcMW7p10pbq6Km7OIG9w4MWLn26u1OsssWjNVOWLhBy7NgPuBW7ivzJGyL43r29a9OJkvHI9PjnlDwA/Z1+Zgc/3HfrOAhVjC5WDC/3nLcbByVsi+YVWzmtgDfUXunimJFUwzPcUW32x+W1kOOaubTaO1RTmaFN0MgL6zniL+Y/yHfzo2Cx6hF1/WaPszZabPlSwrXj1qABG5CKmnJ4+xq94ZMHBSg8RWUyUPKlW/RcAAP//eDJz7qgHAAA="
        },
        "mode": 448
      },
```

[Archive.zip](https://github.com/coreos/butane/files/8124209/Archive.zip)
