### ISSUE TITLE
Append a text with inline after a specific text via regex

### ISSUE THREAD

**Issue by rfakit** [coreos/butane#410]
Hi 
Is there any way to rehearse the file fcct config to append a text after specific line ?
let say we have a text like this 

file.txt
```
line1
line2
specifc line
line3
```
and with the bellow config 
```
    - path: /root/file.txt
      # 420 (decimal) == 644 (octal)
      mode: 420
      user:
        name: root
      group:
        name: root
      append:
        - inline: |
            some text
      after: SPECIFIC LINE
```
so the out put file would like bellow

```
line1
line2
specifc line
some text
line3
```
