### ISSUE TITLE
Cannot add user to the render system group

### ISSUE THREAD

**Issue by MidnessX** [coreos/butane#411]
I'm trying to add a user to the ``render`` group as it should have access to a graphics card passed through by the host.

However, this has proven to be impossible as writing
```
[...]
passwd:
  users:
    - name: myuser
      groups:
        - render
[...]
```
results in ``ignition-files.service`` failing due to the ``render`` group missing, and manually creating the group by doing
```
[...]
passwd:
  groups:
    - name: render
      system: true
  users:
    - name: myuser
      groups:
        - render
[...]
```
instead results in  ``ignition-files.service`` failing due to the ``render`` group already existing.
