### ISSUE TITLE
Possible error in the yaml schema description of the "ssh_authorized_keys_local" directive.

### ISSUE THREAD

**Issue by pol73** [coreos/butane#503]
```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/Relativ-IT/Butane-Schemas/Release/Butane-Schema.json
variant: fcos
version: 1.5.0
passwd:
  users:
    - name: core
      ssh_authorized_keys_local:
        - secret/id_ed25519.pub
```

I have error: "String does not match the pattern of "((.*)\s)?((?:sk-)?(?:ssh|ecdsa)-[a-z0-9@.-]+)\s([a-zA-Z0-9+/]+={0,2})(\s(.*))?".yaml-schema: ssh_authorized_keys (list of strings):".

But this is should be "string" (https://github.com/coreos/butane/blob/main/docs/examples.md#ssh-keys-from-local-files). But not: "#/definitions/patterns/patternProperties/ssh_pub" as in the "ssh_authorized_keys" directive.
