### ISSUE TITLE
Anchor merge key is reported as "Unused key <<"

### ISSUE THREAD

**Issue by richardkraus-adesso** [coreos/butane#507]
Using Anchors in Butane works fine, but when using a [merge key](https://ktomk.github.io/writing/yaml-anchor-alias-and-merge-key.html) a `warning at $.passwd.users.1.<<, line 11 col 7: Unused key <<` is shown when compiling the following config (this also happens for other variants):

```sh
podman run --rm -i quay.io/coreos/butane:latest > /dev/null << EOF
variant: flatcar
version: 1.1.0
passwd:
  users:
    - &nologin-user
      name: test1
      uid: 1000
      shell: /usr/bin/nologin
      no_create_home: true
      no_log_init: true
    - << : *nologin-user
      name: test2
      uid: 1001
EOF
```

This does not break any functionality (at least that Im aware of), but I just find it a little annoying..

**Comment by kj** [comment]
It would also be nice to be able to use an `x-foo` prefix like Docker Compose allows. The output already works fine, but the warning is indeed annoying. I've silenced `Unused key (x-|<<)` lines in my wrapper script in the meantime.

```yaml
x-user: &user
  user:
    name: 'core'
  group:
    name: 'core'

variant: 'fcos'
version: '1.6.0'
storage:
  directories:
    - path: '/home/core/.config'
      <<: &user
    - path: '/home/core/.config/containers'
      <<: &user
    - path: '/home/core/.config/containers/systemd'
      <<: &user
```
