### ISSUE TITLE
Error when trying to use 'files:', 'append:' in butane file

### ISSUE THREAD

**Issue by TeamLinux01** [coreos/butane#531]
I am trying to use the following snippit in my butane file.
```yaml
variant: fcos
version: 1.5.0
...
storage:
...
  files:
    - path: /etc/sysctl.conf
      append:
        inline: "net.ipv4.ip_unprivileged_port_start=80"
...
```

When running the commnd
```shell
podman run -ti --rm --security-opt label=disable -v ./:/pwd --workdir /pwd quay.io/coreos/butane:release --pretty  --strict ucore-autorebase.butane > ucore.ign
```
it has the following error
```
Error translating config: yaml: unmarshal errors:
  line 73: cannot unmarshal !!map into []v0_5.Resource
```

It transpiles correctly if I change `append` to `contents`.
