### ISSUE TITLE
Butane with merge.local does not convert to ignition

### ISSUE THREAD

**Issue by ddt3** [coreos/butane#576]
I am using the following  Butane file that I cannot get to work:
```
variant: fcos
version: 1.5.0
ignition:
  config:
    merge:
    - local: ign/include/ssh.ign
    - local: ign/include/add-compose.ign
    - local: ign/include/music.ign
    - local: ign/include/start-docker.ign
storage:
  files:
  - path: /etc/hostname
    contents:
      inline: examplehost
```
This is the output:
```
$ butane yaml/example-local.yaml -d /home/dries/workspaces/proxmox-coreos 
error at $.ignition.config.merge.1, line 8 col 7: duplicate entry defined
error at $.ignition.config.merge.2, line 9 col 7: duplicate entry defined
error at $.ignition.config.merge.3, line 10 col 7: duplicate entry defined
Error translating config: config generated was invalid

```
When I use source: it just works
``` 
variant: fcos
version: 1.5.0
ignition:
  config:
    merge:
    - source: http://www-fc.familie-dokter.lan/ign/include/ssh.ign
    - source: http://www-fc.familie-dokter.lan/ign/include/add-compose.ign
    - source: http://www-fc.familie-dokter.lan/ign/include/music.ign
    - source: http://www-fc.familie-dokter.lan/ign/include/start-docker.ign
storage:
  files:
  - path: /etc/hostname
    contents:
      inline: examplehost
```

This file converts without a problem to ignition:
```
$ butane yaml/example.yaml
{"ignition":{"config":{"merge":[{"source":"http://www-fc.familie-dokter.lan/ign/include/ssh.ign"},{"source":"http://www-fc.familie-dokter.lan/ign/include/add-compose.ign"},{"source":"http://www-fc.familie-dokter.lan/ign/include/music.ign"},{"source":"http://www-fc.familie-dokter.lan/ign/include/start-docker.ign"}]},"version":"3.4.0"},"storage":{"files":[{"path":"/etc/hostname","contents":{"compression":"","source":"data:,examplehost"}}]}}
```

Specification at: https://coreos.github.io/butane/config-fcos-v1_6/ does not explain why the behavior is different.
