### ISSUE TITLE
Feature Request: Allow specifying ownership for trees

### ISSUE THREAD

**Issue by vgchl** [coreos/butane#577]
When running rootless containers there's a lot of noise in butane files to set files and directories to have the correct ownership. Having the ability to define the ownership for a tree of files would make creating folder structures like `.config/containers/systemd/user/some-service.container` etc far more convenient.

I think this could be a convenient alternative to #380 as well.

For example:

```
trees:
  - path: /home/core/.config
    local: .config
    user:
      name: core   
    group:
      name: core
```
